sudo: required

language: ruby

rvm:
  - 2.2

services:
  - docker

install:
  - bundle install
  - bundle exec berks install

script:
  - bundle exec foodcritic . --exclude test/
  - bundle exec cookstyle
  - bundle exec rspec
  - bundle exec kitchen test


