version: 0.1

phases:
  install:
    commands:
      - sudo apt-get update
      - sudo apt-get install -y curl software-properties-common
      - curl -fsSL https://yum.dockerproject.org/gpg | sudo apt-key add -
      - sudo add-apt-repository "deb https://apt.dockerproject.org/repo/ ubuntu-$(lsb_release -cs) main"
      - sudo apt-get update
      - sudo apt-get install -y wget gdebi apt-transport-https ca-certificates docker-engine
      - wget https://packages.chef.io/stable/ubuntu/12.04/chefdk_1.0.3-1_amd64.deb
      - gdebi -n chefdk_1.0.3-1_amd64.deb
      - wget https://releases.hashicorp.com/packer/0.12.2/packer_0.12.2_linux_amd64.zip
      - unzip packer_0.12.2_linux_amd64.zip
      - sudo mv packer /usr/local/bin
      - wget https://releases.hashicorp.com/terraform/0.8.5/terraform_0.8.5_linux_amd64.zip
      - unzip terraform_0.8.5_linux_amd64.zip
      - sudo mv terraform /usr/local/bin
  pre_build:
    commands:
      - bundle install
      - berks install
      - berks vendor vendor
  build:
    commands:
      - chef exec foodcritic . --exclude test
      - chef exec cookstyle
      - chef exec rspec
      - chef exec kitchen test
  post_build:
    commands:
      - cd packer
      - packer build ami.json
      - cd terraform
      - terraform apply -var "ami=`cat ../packer/ami.txt`"
artifacts:
  files:
    - packer/ami.txt
    - terraform/*.tfstate
