name 'simple_nginx_site'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures simple_nginx_site'
long_description 'Installs/Configures simple_nginx_site'
version '0.1.0'
source_url ''
issues_url ''

depends 'nginx', '~> 2.7'
